sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 47.120.71.197
    port: 3307
    database: sky_take_out
    username: root
    password: Duandongchen123!
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: Uestc
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

  alioss:
    access-key-secret: oikI9wxfv18dKuw7whUg9SIPEyJ4im
    access-key-id: LTAI5tDGJxkv9WbxcgMpbKZS
    bucket-name: sky-take-out-2906910659
    endpoint: oss-cn-beijing.aliyuncs.com